---
title: "Computer responses to key presses"
author: "Carlos Antonio Rodríguez-Saltos"
date: "December 19, 2018"
output: pdf_document
---
This is the documentation of the development of code that controlls responses of the Raspberry Pi to key presses. This document is part of the documentation of the development of the SingSparrow operant-yoked mode. For more information on SingSparrow and on the operant-yoked mode, see the README.md file for SingSparrow.

## Simulating presses
I needed to simulate a generator of key presses and a scanner of presses. Both had to be separate modules, but a bridge had to be set from the generator to the scanner. In this section, I will describe the generator.

In ultimate instance, the generator must be the user (or bird) interacting with the keys connected to the GPIOs of the RPi. But in an initial phase of testing, the generator was me pressing keys on the keyboard of my computer.

I wrote a simple `bash` script to simulate key presses. The script reads key strokes on the keyboard and writes them to a text file that then the scanner will read. In the text file, there are two columns, one for each key. Two keys on the keyboard are selected as the "left" and "right" key equivalents of the RPi set-up. When the user is not pressing those keys, then the generator writes zero; if any key is pressed, it writes one under the corresponding column. To avoid ending with a large file full of zeros, the generator allows the text file to contain only two rows at a time by constantly updating the rows based on new input from the user.

The name of the generator is `press-capture.sh` (it is included in the source folder of this document). The output of the generator can be seen in real time by running `scan_sim-press.sh`.

## Responding to the onset of a press
The Raspberry Pi (RPi) will be constantly scanning for key presses. To detect the onset of a press, the RPi will compare the state of each key to their previous state; a state of 0 (not being pressed) succeeded by a state of 1 (press) is an onset of a press.

In the following example, the program responds to the onset of the press by displaying a text message.

```{bash}
# bash
sim-presses.txt
```

